seed: 1337

data:
  train_csv: data/train.csv
  labels_csv: data/train_labels.csv
  test_csv: data/test.csv
  target_pairs_csv: data/target_pairs.csv
  date_column: date_id
  window: 640  # leverage 32G VRAM for longer temporal context
  patch_len: 16
  patch_stride: 8
  features: null
  channels_first: false
  normalize_per_day: true
  winsorize_p: 0.002

model:
  d_model: 768
  n_heads: 12
  dropout: 0.1
  n_layers_intra: 12
  n_layers_cross: 6
  activation: gelu
  time2vec_dim: 8
  use_flash_attn: true
  use_compile: true
  cross_group_size: 16

train:
  epochs: 40
  batch_days: 18
  grad_accum: 1
  lr_max: 0.0012
  weight_decay: 0.05
  warmup_pct: 0.1
  amp: true
  grad_clip_norm: 0.9
  checkpoint_dir: checkpoints/rtx5090
  save_every: 1
  early_stop_patience: 6
  grad_checkpointing: true
  use_pretrain: true
  pretrain_ckpt: checkpoints/timae_encoder.ckpt
  amp_dtype: bf16
  train_loader:
    num_workers: 12
    pin_memory: true
    persistent_workers: true
    prefetch_factor: 6
    pin_memory_device: cuda
  eval_loader:
    num_workers: 6
    pin_memory: true
    persistent_workers: true

loss:
  diffsort_temperature: 0.08
  diffsort_regularization: none
  stability_lambda: 0.25

cv:
  n_splits: 5
  embargo_days: 4
  test_size_fraction: 0.2
  max_train_dates: null
  use_cpcv: true

inference:
  snapshot: checkpoints/rtx5090/best.ckpt
  tanh_clip: 0.0

pretrain:
  epochs: 12
  lr: 0.001
  weight_decay: 0.05
  mask_ratio: 0.45
  batch_days: 18
  window: 640
  patch_len: 16
  patch_stride: 8
  time2vec_dim: 8

logging:
  log_dir: runs/camht_rtx5090
  csv_log: runs/metrics_rtx5090.csv
